Enhance build validation workflow to handle build failures by uploading test reports and failing the job if necessary

diff --git a/.github/workflows/build-validation.yml b/.github/workflows/build-validation.yml
--- a/.github/workflows/build-validation.yml
+++ b/.github/workflows/build-validation.yml
@@ -42,8 +42,20 @@ jobs:
       uses: gradle/gradle-build-action@v2
 
     - name: Build with Gradle
-      run: ./gradlew build --stacktrace
+      run: ./gradlew build || echo "BUILD_FAILED=true" >> $GITHUB_ENV
+      continue-on-error: true
     
+    - name: Upload test reports if tests failed
+      if: env.BUILD_FAILED == 'true'
+      uses: actions/upload-artifact@v4
+      with:
+        name: Unit Test Reports
+        path: '**/build/reports/tests/test'
+        if-no-files-found: ignore  # Prevents errors if no reports exist
+    
+    - name: Fail the job if build failed
+      if: env.BUILD_FAILED == 'true'
+      run: exit 1
 
       # TODO: Move the sidecar into a central image repository
     - name: Initialize Durable Task Sidecar
