use jdk11 for unit tests

diff --git a/.github/workflows/build-validation.yml b/.github/workflows/build-validation.yml
--- a/.github/workflows/build-validation.yml
+++ b/.github/workflows/build-validation.yml
@@ -45,7 +45,9 @@ jobs:
       run: ./gradlew build -x test
     
     - name: Run Unit Tests with Gradle
-      run: ./gradlew clean test || echo "UNIT_TEST_FAILED=true" >> $GITHUB_ENV
+      run: |
+        export JAVA_HOME=$JDK_11
+        ./gradlew clean test || echo "UNIT_TEST_FAILED=true" >> $GITHUB_ENV
       continue-on-error: true
 
     - name: Upload test reports if tests failed
